spring:
  application:
    name: review-service
  cloud:
    fail-fast: true
    password: ${CONFIG_SERVICE_PASSWORD}
    username: user
  config:
    import: optional:configserver:http://localhost:8888
