eureka: # eureka client 是每个服务都要有的
  instance:
    prefer-ip-address: true # 在Eureka服务注册表中，是否优先使用IP地址而不是主机名来表示服务实例
  client:
    serviceUrl: # registry
      defaultZone: http://localhost:8762/eureka/ # 指定了Eureka服务器的地址。客户端（即服务实例）使用这个URL来注册自己，以及查找其他服务实例

#security:
#  oauth2:
#    resource:
#      user-info-uri: http://localhost:5000/uaa/users/current # auth-service

spring:
  rabbitmq:
    host: localhost
    port: 5672
#    virtual-host: /myTravel # 每个user有一个自己的虚拟主机，以便于隔离，默认是/
    username: guest
    password: guest

resilience4j.circuitbreaker:
  configs:
    default:
      minimumNumberOfCalls: 5 # 最小调用次数为5次
      permittedNumberOfCallsInHalfOpenState: 3
      waitDurationInOpenState: 10s # 时间窗口为10秒
      failureRateThreshold: 50 # 失败率阈值为50％
      ringBufferSizeInClosedState: 5 # 断路器在闭合状态下的环形缓冲区大小为5
      ringBufferSizeInHalfOpenState: 3 # 在半开状态下的环形缓冲区大小为3


