server:
  port: 7000
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/mytravel?useSSL=false&autoReconnect=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 85961030

mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.mytravel.authservice.entity.dto

management:
  tracing:
    sampling:
      probability: 1.0 # 采样率100%

logging:
  pattern:
    level: ${spring.application.name:}, %X{traceId:-}, %X{spanId:-}
